name: build-code

on:
   pull_request:
      branches:
         - 'develop'
         - 'main'

jobs:
   build:
      runs-on: ubuntu-latest
      env:
         NODE_VERSION: '22'

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: ${{ env.NODE_VERSION }}

         - name: Install yarn
           run: corepack enable yarn

         - name: Install dependencies
           run: yarn install

         - name: Build the project
           run: yarn build
